// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxl0VePx88HoK7ZwXDleFBh-KMRc3yp-0',
    appId: '1:937244764980:web:44705689bcdb292052d361',
    messagingSenderId: '937244764980',
    projectId: 'coco-contentstrategist-ai',
    authDomain: 'coco-contentstrategist-ai.firebaseapp.com',
    storageBucket: 'coco-contentstrategist-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFCnxSdbpaOzGZrw8Nu11jRp01aSTO2TQ',
    appId: '1:937244764980:android:aa237c7a2965c03b52d361',
    messagingSenderId: '937244764980',
    projectId: 'coco-contentstrategist-ai',
    storageBucket: 'coco-contentstrategist-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZVv4PfFqAOV1TCk1gSNxuuP98IkC-CyQ',
    appId: '1:937244764980:ios:741d60b7faff949552d361',
    messagingSenderId: '937244764980',
    projectId: 'coco-contentstrategist-ai',
    storageBucket: 'coco-contentstrategist-ai.firebasestorage.app',
    iosBundleId: 'com.example.contentAi',
  );

}